##
## Build with Travis.CI
##
language: r
cache: packages
sudo: false
r:
  - oldrel
  - release
  - devel
after_script:
  - R -e 'r<-devtools::install_github("thomasWeise/dataManageR"); if(r) { cat("OK\n"); q(safe="no", status=0); } else { cat("error: ", r, "\n", sep="", collapse=""); q(safe="no", status=1); }'
